import React from 'react';
import {FormattedHTMLMessage} from 'react-intl';

const CalculatorPageStep3 = () => (
  <div>
    <div className="steps-content">
      <h2><FormattedHTMLMessage
        id="ManualPageStep3.title"
        defaultMessage="Ready to proceed?"
      /></h2>
      {/* <center>
        <img style={{maxWidth: '480px'}} src="/images/input_folder.png" alt="Is everything ready?"/>
      </center> */}
      <br/>
      <p><FormattedHTMLMessage
        id="ManualPageStep3.body"
        defaultMessage="After opening the calculator, close the text file demonstrating the functionalities (use the x button next to the name). As the next step, open the prepared files that are saved in the <b>catalog</b>."
      /></p>
      {/* <p>
        Kalkulator jest anonimowy - nie wymaga rejestracji.
        Kalkulator jest prywatny - historia transakcji oraz wynik nigdzie nie jest wysyłany -
        wszystkie obliczenia wykonywane są na Twoim komputerze - nikt poza Tobą nie ma wglądu w Twoje dane.
      </p> */}
      <p><FormattedHTMLMessage
        id="ManualPageStep3.footer"
        defaultMessage="<strong>Disclaimer:</strong><br/>The tool is designed to ease the calculation of the profit made on cryptocurrency trading and help to manage a cryptocurrency portfolio. The author denies any liabilities for the results generated by the application as it might contain bugs or it can fail to meet some other requirements. <strong>You agree to use the application at solely your risk.</strong> It is advised to consult the results with a tax advisor."
      /></p>
    </div>
  </div>
);

export default CalculatorPageStep3;
